### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by Rannie999** [therealcooperpark/hero#1] opened 2021-02-24 03:19 UTC
Dear developers,
I'm trying to use sidekick for renaming alignment headers. Linux version I use is CentOS Linux release 7.8.2003 (Core). When I run the tutorial without the option of "--cpus", it works fine but when I run both tutorial and my sample with the option, I have this error message shows below. 
When I run my samples without the option of "--cpus", the program hung for a long time (>24h) and did not process it anymore, though it did rename some files at the beginning.

command line:
```
#!/bin/bash
source /opt/asn/etc/asn-bash-profiles-special/modules.sh
module load intel/18.0.3.222 gnu_parallel/201612222
./sidekick.py ./gff_table --alns ../pan_genome_sequences --fastgear /mnt/beegfs/apps/dmc/apps/fastgear_2016/src/fastGEARpackageLinux64bit/run_fastGEAR.sh
 --mcr /mnt/beegfs/apps/dmc/apps/matlab_runenv_r2016a/v901 --output sidekick_genes --fgout fastgear_genes --cpus 16
```
Error:
> Starting rename process!
> Traceback (most recent call last):
>   File "./sidekick.py", line 221, in <module>
>     main()
>   File "./sidekick.py", line 208, in main
>     pool = multiprocessing.Pool(processes=args.cpus)
>   File "/usr/lib64/python3.6/multiprocessing/context.py", line 119, in Pool
>     context=self.get_context())
>   File "/usr/lib64/python3.6/multiprocessing/pool.py", line 166, in __init__
>     if processes < 1:
> TypeError: '<' not supported between instances of 'str' and 'int'

#
I tried to edit the sidekick.py script in places where the error "pool = multiprocessing.Pool(processes=args.cpus)" was reported. 
When I run the edited script with option of "--cpus" with data in the tutorial, it did not report the above TypeError and work very quickly. But when I run it with my sample, it still got stuck just like before. 
I am not familiar with python so maybe I was wrong about the changes, which could make it hang.

original script:
>  Assume ~ 4 cpus per job. Also, just don't submit all jobs at once!
> j = cpus // 4 if cpus > 8 else 1
> …..
>     print('Starting rename process!')
>     pool = multiprocessing.Pool(processes=args.cpus)
>     status = pool.map(rename_alignment, gene_alns)
>     pool.close()
>     pool.join()squirrels

Edited script (edited codes are in bold):
>   Assume ~ 4 cpus per job. Also, just don't submit all jobs at once!
> j = **int(**cpus**)** // 4 if **int(**cpus**)** > 8 else 1
> ….
>     print('Starting rename process!')
>     pool = multiprocessing.Pool(processes=**int(**args.cpus**)**)
>     status = pool.map(rename_alignment, gene_alns)
>     pool.close()
> pool.join()~~squirrels~~

Messages after I interrupted the stuck program:
> Traceback (most recent call last):
> Process ForkPoolWorker-132:
>   File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/lib64/python3.6/multiprocessing/pool.py", line 108, in worker
>     task = get()
>   File "/usr/lib64/python3.6/multiprocessing/queues.py", line 334, in get
>     with self._rlock:
>   File "/usr/lib64/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
>     return self._semlock.__enter__()

My samples are ~16400 alignment files. So I really need more cpus to process them. It seems there is something wrong with multiprocessing.
I also tried to run the original script and the edited script with different python versions like 3.6, 3.7, 3.8. None of them works.

Could you help me check it?
Thank you so much in advance!

**Comment by therealcooperpark** [comment] 2021-03-03 21:28
Hello!

So sorry about the delay, I didn't receive any email or anything about this issue and I don't actively work on this project much anymore.

I found the issue with the cpus argument and have pushed a fix for it. Please pull the new version of sidekick.py and it should resolve your issues with the error message. (For what it's worth, you were basically correct with your fix. My argument definitions were not robust enough and when users provided their own thread value it could turn an int to a str).

How many samples are in each of your alignment files? The hanging is unusual and not something I can reproduce with my current data. The renaming process can be considerably slow with large datasets as the multithreading tackles multiple files at once rather than more efficiently parsing single files.

I'll close this ticket since I believe I have resolved the primary concern. If you still experience hanging after this fix feel free to open a new ticket and I can investigate that more closely.

**Closed as completed by therealcooperpark** 2021-03-03 21:28 UTC

**Comment by Rannie999** [comment] 2021-03-08 02:49
Problem solved. Many thanks!
